server:
  port: 8081


spring:
  profiles:
    active: dev,es,rabbit,redis,sms,db,activiti,quartz
  # spring-activiti
  # 自动部署验证设置:true-开启（默认）、false-关闭
  # asyncExecutorEnabled属性设置设置true后将代替那些老的Job executor
  # asyncExecutorActivate是指activiti在流程引擎启动就激活AsyncExecutor,异步：true-开启（默认）、false-关闭
  activiti:
    check-process-definitions: true
    async-executor-activate: false
    async-executor-enabled: false
    job-executor-activate: false
  thymeleaf:
    cache: false
#  data:
#    mongodb:
#      host: 106.14.216.218
#      port: 27017
#      database: test
#      uri: mongodb://106.14.216.218/test
#      username: root
#      password: 123456
#


swagger:
  enable: true

zimuzu:
  token_url: http://a.zmzapi.com/index.php?g=api/public&m=v2&accesskey=519f9cab85c8059d17544947k361a827&client=2&a=login
  username: jien007
  password: jien007
  activity_url: http://h5.rrhuodong.com/index.php?g=api/mission&m=index&a=login
  login_url: http://h5.rrhuodong.com/index.php?g=api/mission&m=clock&a=store&id=2
  info_url: http://h5.rrhuodong.com/index.php?g=api/mission&m=index&a=user_info
  python_position: ${zimuzu.dev.python_position}
  prd:
    python_position: C://Users/info/Documents/myJee/modules/src/main/resources/zimuzu.py
  dev:
    python_position: C://Users/info/Documents/myJee/modules/src/main/resources/zimuzu.py

